
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

# Uncomment below services if you want to add more functionality
#  db:
#    image: postgres:14-alpine
#    environment:
#      POSTGRES_PASSWORD: example
#      POSTGRES_USER: admin
#      POSTGRES_DB: appdb
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    restart: unless-stopped
#
#  redis:
#    image: redis:alpine
#    restart: unless-stopped
#    volumes:
#      - redis-data:/data
#
#volumes:
#  db-data:
#  redis-data:
